### ISSUE TITLE
When Monkey launches 2.birthdroid.apk, there is no instrumentation output in the trace.log

### ISSUE THREAD

**Issue by fwt1888** [resess/Mandoline#10]
Hello! 
Recently I wanted to try to slice apk files with Mandoline. Currently, when running 1.anki.apk through Monkey, I can get the following instrumentation results: 
```
SLICING: ZLIB: eJzlmVuuJSYORUfUEvgF1   (omitted)
SLICING: ZLIB: eJztmVuOEzEQRVeEZJfLr9  (omitted)
```
However, when I tried to analyze 2. birthdroid.apk and Merge1.apk( in DroidBench), I found no similar information output in trace_full.log. I changed the -c option and the number of runs in the following command, but still can't get the result.
`command_output("adb", "-s", device_id, "shell", "monkey", "-p", package_name, "-c", "android.intent.category.LAUNCHER", "1")`
Do you know how to solve it？Thanks!

**Comment by khaled-e-a** [comment]
Hi 
Can you please share with me the commands you used? 
I ran 
`python3 run_app.py ../Dataset/2.birthdroid/2.birthdroid.apk temp/ emulator-5554` 
then played with the app then ran
`python3 extract_trace.py emulator-5554 temp/trace.log` and the trace lines are there. 
Did you trigger the app?  Did you see that the monkey clicks actually exercise the app?

**Comment by fwt1888** [comment]
Hi
First I ran `start /b emulator.exe -avd Pixel_2_API_30 -no-boot-anim -no-snapshot -noaudio -gpu off` to start the android virtual device, 
then I ran the following commands to use Monkey,
```adb -s emulator-5554 uninstall com.rigid.birthdroid >NUL 2>&1
adb -s emulator-5554 logcat -c
adb -s emulator-5554 logcat -G 100M
adb -s emulator-5554 shell pm list packages | findstr com.rigid.birthdroid
adb -s emulator-5554 shell monkey -p com.rigid.birthdroid -c android.intent.category.LAUNCHER 1
```
finally I ran 
```adb -s emulator-5554 logcat -d > results/slicer/birthdroid/trace_full.log
adb -s emulator-5554 logcat -d | findstr /c:"SLICING" /c:"Timer:" > results/slicer/birthdroid/trace.log
``` 
to get the trace lines.

Is the running result related to the configuration of the android virtual device? 
The virtual device I created is based on android 11.0 api 30. 
Could you please tell me the configuration of your virtual machine？Thanks

**Comment by fwt1888** [comment]
I just read the published paper, changed the avd to Pixel_2_API_28, and did not disable the audio function when starting the avd. However, I still cannot get the output in trace.log. 
In addition, when slicing 1.anki.apk, I found that there is no statement numbered 450275 in static-log.log.
Any possible solution will be great help for me. Thanks!

**Comment by khaled-e-a** [comment]
The emulator I used is Pixel_2_API_28. 
Since you get some trace for 1.anki.apk, it seems like the instrumentation is fine, did you check on the emulator that the other app launched? was there any crashes in the android logcat? 
Also, the statement numbers may vary from trace to trace depending on the run, the "450275" is the statement I choose to slice from in the README as an example, but you'll need to select a different number based on your ICDG file.

**Comment by fwt1888** [comment]
Thanks for your prompt reply！

After I updated the Google Play Services of the emulator, many apk files can generate trace lines in trace.log, but birthdroid.apk cannot. I also tried creating some birthdays in the Google Contacts application, but it didn't work. 

The following is the information related to Monkey in trace_full.log. I have checked the information in it many times and found no obvious mistakes. It makes me feel confused.
```
03-30 08:10:03.616 24109 24109 W Monkey  : args: [-p, com.rigid.birthdroid, -c, android.intent.category.LAUNCHER, 1]
03-30 08:10:03.616 24109 24109 W Monkey  :  arg: "-p"
03-30 08:10:03.616 24109 24109 W Monkey  :  arg: "com.rigid.birthdroid"
03-30 08:10:03.616 24109 24109 W Monkey  :  arg: "-c"
03-30 08:10:03.616 24109 24109 W Monkey  :  arg: "android.intent.category.LAUNCHER"
03-30 08:10:03.616 24109 24109 W Monkey  :  arg: "1"
03-30 08:10:03.617 24109 24109 W Monkey  : data="com.rigid.birthdroid"
03-30 08:10:03.617 24109 24109 W Monkey  : data="android.intent.category.LAUNCHER"
03-30 08:10:03.634  1870  1884 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{5e67cd2 u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{99751a3 24109 (unknown name)/2000/u-1 remote:3cfa134}: process gone or crashing
03-30 08:10:03.651  1870  1927 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.rigid.birthdroid/.BirthdroidActivity} from uid 2000
03-30 08:10:03.651  1870  1927 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
03-30 08:10:03.651  1870  1927 W Binder  : java.lang.Throwable
03-30 08:10:03.651  1870  1927 W Binder  : 	at android.os.BinderProxy.transact(Binder.java:1114)
03-30 08:10:03.651  1870  1927 W Binder  : 	at android.app.IActivityController$Stub$Proxy.activityStarting(IActivityController.java:176)
03-30 08:10:03.651  1870  1927 W Binder  : 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:737)
03-30 08:10:03.651  1870  1927 W Binder  : 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:544)
03-30 08:10:03.651  1870  1927 W Binder  : 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1099)
03-30 08:10:03.651  1870  1927 W Binder  : 	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:486)
03-30 08:10:03.651  1870  1927 W Binder  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5120)
03-30 08:10:03.651  1870  1927 W Binder  : 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5094)
03-30 08:10:03.651  1870  1927 W Binder  : 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5085)
03-30 08:10:03.651  1870  1927 W Binder  : 	at android.app.IActivityManager$Stub.onTransact$startActivity$(IActivityManager.java:10084)
03-30 08:10:03.651  1870  1927 W Binder  : 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:122)
03-30 08:10:03.651  1870  1927 W Binder  : 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3291)
03-30 08:10:03.651  1870  1927 W Binder  : 	at android.os.Binder.execTransact(Binder.java:731)
03-30 08:10:03.680 24109 24109 I Monkey  : Events injected: 1
03-30 08:10:03.688  1870  1870 V SettingsProvider: Notifying for 0: content://settings/system/accelerometer_rotation
03-30 08:10:03.696 24109 24109 I Monkey  : ## Network stats: elapsed time=44ms (0ms mobile, 0ms wifi, 44ms not connected)
03-30 08:10:03.699 24109 24109 I app_process: System.exit called, status: 0
03-30 08:10:03.699 24109 24109 I AndroidRuntime: VM exiting with result code 0.
03-30 08:10:03.701 24121 24121 W igid.birthdroi: Unexpected CPU variant for X86 using defaults: x86_64
03-30 08:10:03.704 24121 24121 E igid.birthdroi: Not starting debugger since process cannot load the jdwp agent.
03-30 08:10:03.690  1870  1870 V SettingsProvider: Notifying for 0: content://settings/system/accelerometer_rotation
03-30 08:10:03.705  1870  1886 I ActivityManager: Start proc 24121:com.rigid.birthdroid/u0a109 for activity com.rigid.birthdroid/.BirthdroidActivity
03-30 08:10:03.734  1624  1624 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 7753728
03-30 08:10:03.740  1870  1929 D         : HostConnection::get() New Host Connection established 0x713beb779500, tid 1929
03-30 08:10:03.741 24121 24121 I igid.birthdroi: The ClassLoaderContext is a special shared library.
03-30 08:10:03.744 24121 24121 W igid.birthdroi: resources.arsc in APK '/data/app/com.rigid.birthdroid-kWGPY0XQDl7qqef_1vBzWQ==/base.apk' is compressed.
03-30 08:10:03.780 24121 24121 V Birthdroid/Birthdays: Sorting by UPCOMING_DAYS
03-30 08:10:03.796 24121 24121 D OpenGLRenderer: HWUI GL Pipeline
03-30 08:10:03.804 24121 24121 V Birthdroid/Birthdays: Sorting by UPCOMING_DAYS
03-30 08:10:03.824  1624  1624 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 7753728
03-30 08:10:03.828  1719  1746 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
03-30 08:10:03.865  1624  1624 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 7753728
03-30 08:10:03.867 24121 24137 D         : HostConnection::get() New Host Connection established 0x713bff174aa0, tid 24137
03-30 08:10:03.871  1624  1624 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 7753728
03-30 08:10:03.872  2000  2267 D EGL_emulation: eglMakeCurrent: 0x713c00a37680: ver 2 0 (tinfo 0x713c00a93460)
03-30 08:10:03.872  1870  1981 I GnssLocationProvider: WakeLock acquired by sendMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@963ad7)
03-30 08:10:03.873  1870  1883 I GnssLocationProvider: WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@963ad7)
03-30 08:10:03.875  1624  1624 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 7753728
03-30 08:10:03.875 24121 24137 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
03-30 08:10:03.876 24121 24137 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
03-30 08:10:03.876 24121 24137 I OpenGLRenderer: Initialized EGL, version 1.4
03-30 08:10:03.876 24121 24137 D OpenGLRenderer: Swap behavior 1
03-30 08:10:03.876 24121 24137 W OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
03-30 08:10:03.876 24121 24137 D OpenGLRenderer: Swap behavior 0
03-30 08:10:03.887 24121 24137 D EGL_emulation: eglCreateContext: 0x713bfd611400: maj 2 min 0 rcv 2
03-30 08:10:03.917 24121 24137 D EGL_emulation: eglMakeCurrent: 0x713bfd611400: ver 2 0 (tinfo 0x713bfd6ab600)
03-30 08:10:03.921  1719  1742 E SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
03-30 08:10:03.947  2000  2267 D EGL_emulation: eglMakeCurrent: 0x713c00a37680: ver 2 0 (tinfo 0x713c00a93460)
03-30 08:10:03.950 24121 24137 D EGL_emulation: eglMakeCurrent: 0x713bfd611400: ver 2 0 (tinfo 0x713bfd6ab600)
03-30 08:10:04.007  2000  2267 D EGL_emulation: eglMakeCurrent: 0x713c00a37680: ver 2 0 (tinfo 0x713c00a93460)
03-30 08:10:04.034  1870  1892 I ActivityManager: Displayed com.rigid.birthdroid/.BirthdroidActivity: +351ms
03-30 08:10:04.043 16501 16501 I GoogleInputMethod: onFinishInput() : Dummy InputConnection bound
03-30 08:10:04.051  2000  2267 D EGL_emulation: eglMakeCurrent: 0x713c00a37680: ver 2 0 (tinfo 0x713c00a93460)
03-30 08:10:04.085  2000  2267 D EGL_emulation: eglMakeCurrent: 0x713c00a37680: ver 2 0 (tinfo 0x713c00a93460)
03-30 08:10:04.117  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.118  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.119  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.120  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.120 16271 17102 D EGL_emulation: eglMakeCurrent: 0x713c00a3aba0: ver 2 0 (tinfo 0x713c00ad33c0)
03-30 08:10:04.121  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.122  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.122  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.122  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.123  2490  2644 D EGL_emulation: eglMakeCurrent: 0x713c00a39160: ver 2 0 (tinfo 0x713c00a0da80)
03-30 08:10:04.123  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.124  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.124  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.125  1719  1746 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.125  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.126  1719  1746 D         : HostConnection::get() New Host Connection established 0x7272e1dd3de0, tid 1746
03-30 08:10:04.126  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.127  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.127  1719  1746 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.127  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.128  1719  1746 D         : HostConnection::get() New Host Connection established 0x7272e1dd3de0, tid 1746
03-30 08:10:04.128  2000  2267 D EGL_emulation: eglMakeCurrent: 0x713c00a37680: ver 2 0 (tinfo 0x713c00a93460)
03-30 08:10:04.128  1719  1746 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.128  1719  1746 D         : HostConnection::get() New Host Connection established 0x7272e1dd3de0, tid 1746
03-30 08:10:04.129  1719  1746 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.130  1719  1746 D         : HostConnection::get() New Host Connection established 0x7272e1dd3de0, tid 1746
03-30 08:10:04.130  1719  1746 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.131  1719  1746 D         : HostConnection::get() New Host Connection established 0x7272e1dd3de0, tid 1746
03-30 08:10:04.131  1719  1746 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.131  1719  1746 D         : HostConnection::get() New Host Connection established 0x7272e1dd3de0, tid 1746
03-30 08:10:04.132  1719  1746 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.134  1719  1746 D         : HostConnection::get() New Host Connection established 0x7272e1dd3de0, tid 1746
03-30 08:10:04.134  1719  1746 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.140  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.160  1719  1719 W SurfaceFlinger: couldn't log to binary event log: overflow.
03-30 08:10:04.160 16271 24140 I PBSessionCacheImpl: (REDACTED) Deleted sessionId[%d] from persistence.
03-30 08:10:04.160  1719  1719 W SurfaceFlinger: couldn't log to binary event log: overflow.
03-30 08:10:04.168 16271 16323 I A       : getLocaleToModelSpecsMap
03-30 08:10:04.170 16271 16323 I A       : getLocaleToModelSpecsMap
03-30 08:10:04.170 16271 16323 W SearchServiceCore: Abort, client detached.
03-30 08:10:04.173 16271 16323 I MicroDetectionState: (REDACTED) #takeChangeMicroDetectorMode [mIsBargeInEnabled: %b, mCurrentDetectionMode: %s]
03-30 08:10:04.173 16271 16323 I MicroDetectionState: (REDACTED) Should stop hotword detection immediately - %b
03-30 08:10:04.173 16271 16323 I A       : getLocaleToModelSpecsMap
03-30 08:10:04.174 16271 16323 I A       : getLocaleToModelSpecsMap
03-30 08:10:04.189  2000  2267 D EGL_emulation: eglMakeCurrent: 0x713c00a37680: ver 2 0 (tinfo 0x713c00a93460)
03-30 08:10:04.206  2000  2267 D EGL_emulation: eglMakeCurrent: 0x713c00a37680: ver 2 0 (tinfo 0x713c00a93460)
03-30 08:10:04.217  1870  1929 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.217  1870  1929 D         : HostConnection::get() New Host Connection established 0x713beb779500, tid 1929
03-30 08:10:04.219  1870  1929 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.244  1870  1929 D         : HostConnection::get() New Host Connection established 0x713c00b385e0, tid 1929
03-30 08:10:04.244  1870  1929 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.245  1870  1929 D         : HostConnection::get() New Host Connection established 0x713c00b385e0, tid 1929
03-30 08:10:04.248  1870  1929 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.248  1719  1742 W SurfaceFlinger: Attempting to set client state on removed layer: Splash Screen com.rigid.birthdroid#0
03-30 08:10:04.249  1719  1742 W SurfaceFlinger: Attempting to destroy on removed layer: Splash Screen com.rigid.birthdroid#0
03-30 08:10:04.256  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.256  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.257  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.258  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.258  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.259  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
03-30 08:10:04.260  1897  1897 D gralloc_ranchu: gralloc_unregister_buffer: exiting HostConnection (is buffer-handling thread)
03-30 08:10:04.268  2000  2267 D EGL_emulation: eglMakeCurrent: 0x713c00a37680: ver 2 0 (tinfo 0x713c00a93460)
03-30 08:10:04.275  1897  1897 D         : HostConnection::get() New Host Connection established 0x71caea82e480, tid 1897
```

**Comment by khaled-e-a** [comment]
Do you have any instrumentation issues perhaps? do you see any errors in the output/instr-log.log?

**Comment by fwt1888** [comment]
I checked the instr-log.log file, and did not find any error unfortunately. Could you please send the birthdroid_i.apk that has been instrumented and signed to my email (on my profile)? I want to verify whether there is a problem with the instrumentation or the signature. 

If I still cannot find out the reason, I can only give up slicing this apk file. Thanks for so many days of reply!

**Comment by khaled-e-a** [comment]
I sent you the instrumented apk via email, please let me know the results of your verification.
